# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Methylation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Methylation.proto',
  package='lm.io',
  syntax='proto3',
  serialized_pb=_b('\n\x11Methylation.proto\x12\x05lm.io\"\\\n\x0bMethylation\x12\r\n\x05rname\x18\x01 \x01(\t\x12\x0b\n\x03pos\x18\x02 \x01(\x05\x12\r\n\x05\x63igar\x18\x03 \x01(\t\x12\n\n\x02xm\x18\x04 \x01(\t\x12\n\n\x02xr\x18\x05 \x01(\t\x12\n\n\x02xg\x18\x06 \x01(\tb\x06proto3')
)




_METHYLATION = _descriptor.Descriptor(
  name='Methylation',
  full_name='lm.io.Methylation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rname', full_name='lm.io.Methylation.rname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos', full_name='lm.io.Methylation.pos', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cigar', full_name='lm.io.Methylation.cigar', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='xm', full_name='lm.io.Methylation.xm', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='xr', full_name='lm.io.Methylation.xr', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='xg', full_name='lm.io.Methylation.xg', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=120,
)

DESCRIPTOR.message_types_by_name['Methylation'] = _METHYLATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Methylation = _reflection.GeneratedProtocolMessageType('Methylation', (_message.Message,), dict(
  DESCRIPTOR = _METHYLATION,
  __module__ = 'Methylation_pb2'
  # @@protoc_insertion_point(class_scope:lm.io.Methylation)
  ))
_sym_db.RegisterMessage(Methylation)


# @@protoc_insertion_point(module_scope)
