#!/usr/bin/env python
import sys

from robertslab.sfile import *

# Make sure we have the correct command line arguments.
if len(sys.argv) < 2:
    print "Usage: command [input_filename]"
    quit()

command = sys.argv[1]
if len(sys.argv) == 3:
    f=SFile.fromFilename(sys.argv[2], 'rb')
else:
    f=SFile(sys.stdin)

# Open the file.
while True:
    r=f.readNextRecord()
    if r == None:
        break
    f.skipData(r.dataSize)
    print r
    
f.close()

